services:
  phpmyadmin:
    container_name: phpmyadmin2
    image: phpmyadmin/phpmyadmin
    #links:
        #- mysql:mysql
    ports:
        - 8086:80
    restart: always
    environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        MYSQL_USER: root
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    #depends_on:
      #mysql:
        #condition: service_healthy
    networks:
        - local-network

networks:
    local-network:
        external: true